package stevesaddons.reference;

import java.util.Arrays;

import cpw.mods.fml.common.ModMetadata;
import stevesaddons.StevesAddons;
import stevesaddons.Tags;

public class Metadata {

    public static ModMetadata init(ModMetadata metadata) {
        metadata.modId = StevesAddons.ID;
        metadata.name = StevesAddons.NAME;
        metadata.description = "Adds extra things to improve SFM";
        metadata.url = "https://github.com/hilburn/StevesAddons";
        metadata.version = Tags.VERSION;
        metadata.authorList = Arrays.asList("hilburn");
        metadata.credits = "";
        metadata.autogenerated = false;
        return metadata;
    }
}
